/*
 * Bandwidth.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Bandwidth.Standard;
using Bandwidth.Standard.Utilities;

namespace Bandwidth.Standard.Messaging.Models
{
    public class BandwidthMessageItem 
    {
        public BandwidthMessageItem() { }

        public BandwidthMessageItem(string messageId = null,
            string accountId = null,
            string sourceTn = null,
            string destinationTn = null,
            string messageStatus = null,
            string messageDirection = null,
            string messageType = null,
            int? segmentCount = null,
            int? errorCode = null,
            string receiveTime = null,
            string carrierName = null)
        {
            MessageId = messageId;
            AccountId = accountId;
            SourceTn = sourceTn;
            DestinationTn = destinationTn;
            MessageStatus = messageStatus;
            MessageDirection = messageDirection;
            MessageType = messageType;
            SegmentCount = segmentCount;
            ErrorCode = errorCode;
            ReceiveTime = receiveTime;
            CarrierName = carrierName;
        }

        /// <summary>
        /// Getter for messageId
        /// </summary>
        [JsonProperty("messageId", NullValueHandling = NullValueHandling.Ignore)]
        public string MessageId { get; set; }

        /// <summary>
        /// Getter for accountId
        /// </summary>
        [JsonProperty("accountId", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountId { get; set; }

        /// <summary>
        /// Getter for sourceTn
        /// </summary>
        [JsonProperty("sourceTn", NullValueHandling = NullValueHandling.Ignore)]
        public string SourceTn { get; set; }

        /// <summary>
        /// Getter for destinationTn
        /// </summary>
        [JsonProperty("destinationTn", NullValueHandling = NullValueHandling.Ignore)]
        public string DestinationTn { get; set; }

        /// <summary>
        /// Getter for messageStatus
        /// </summary>
        [JsonProperty("messageStatus", NullValueHandling = NullValueHandling.Ignore)]
        public string MessageStatus { get; set; }

        /// <summary>
        /// Getter for messageDirection
        /// </summary>
        [JsonProperty("messageDirection", NullValueHandling = NullValueHandling.Ignore)]
        public string MessageDirection { get; set; }

        /// <summary>
        /// Getter for messageType
        /// </summary>
        [JsonProperty("messageType", NullValueHandling = NullValueHandling.Ignore)]
        public string MessageType { get; set; }

        /// <summary>
        /// Getter for segmentCount
        /// </summary>
        [JsonProperty("segmentCount", NullValueHandling = NullValueHandling.Ignore)]
        public int? SegmentCount { get; set; }

        /// <summary>
        /// Getter for errorCode
        /// </summary>
        [JsonProperty("errorCode", NullValueHandling = NullValueHandling.Ignore)]
        public int? ErrorCode { get; set; }

        /// <summary>
        /// Getter for receiveTime
        /// </summary>
        [JsonProperty("receiveTime", NullValueHandling = NullValueHandling.Ignore)]
        public string ReceiveTime { get; set; }

        /// <summary>
        /// Getter for carrierName
        /// </summary>
        [JsonProperty("carrierName", NullValueHandling = NullValueHandling.Ignore)]
        public string CarrierName { get; set; }

    }
}